### ISSUE TITLE
Switching between tabs and text replaced

### ISSUE THREAD

**Issue by airstep** [agrabhi/logcat#1]
If I switch to other tab with text - it will add logcat output at the end of my file... 
And better to name untiled like 'date_yy_mm_DD_HH__SS.log'

**Comment by agrabhi** [comment]
I have done the code for having a better name, but some bug with untitled scheme of vscode. cant get it work perfectly. working on it.

**Comment by agrabhi** [comment]
fixed the issue in 0.0.5 please update your code.
